/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BetFactory } from "./BetFactory";
export type { BetMarket } from "./BetMarket";
export type { OptimisticResultOracle } from "./OptimisticResultOracle";
