/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { Ownable } from "./@openzeppelin/contracts/access/Ownable";
export { Ownable__factory } from "./factories/@openzeppelin/contracts/access/Ownable__factory";
export type { Pausable } from "./@openzeppelin/contracts/security/Pausable";
export { Pausable__factory } from "./factories/@openzeppelin/contracts/security/Pausable__factory";
export type { IERC20 } from "./@openzeppelin/contracts/token/ERC20/IERC20";
export { IERC20__factory } from "./factories/@openzeppelin/contracts/token/ERC20/IERC20__factory";
export type { BetFactory } from "./contracts/BetFactory";
export { BetFactory__factory } from "./factories/contracts/BetFactory__factory";
export type { BetMarket } from "./contracts/BetMarket";
export { BetMarket__factory } from "./factories/contracts/BetMarket__factory";
export type { OptimisticResultOracle } from "./contracts/OptimisticResultOracle";
export { OptimisticResultOracle__factory } from "./factories/contracts/OptimisticResultOracle__factory";
